### PR TITLE
Add babel-minify-standalone

### LINKED ISSUE #671: Migrate babili-standalone to this repo
Follow up on https://github.com/babel/babel/pull/6029 by moving `babili-standalone` from the babel-standalone repo into this repo.

Reuse the same Gulp + Webpack configuration - `require('babel-standalone/src/gulpTasks.js`) should work to pull in the shared Gulp tasks.

Current package.json: https://github.com/babel/babel-standalone/blob/master/packages/babili-standalone/package.json
Current Gulp script: https://github.com/babel/babel-standalone/blob/master/gulpfile.js#L89-L97

### PR DESCRIPTION
**Pull request by boopathi**
+ Close #671

### CODE REVIEW

**Comment by Daniel15** [comment]
I haven't looked at this in detail yet (not at my computer), but please reuse the infra such as the Webpack config from babel-standalone rather than doing something totally different. Please see the existing babili-standalone build (in the https://github.com/babel/babel-standalone repo) for guidance. 

The Gulp task for Babel-standalone is designed to be reusable so it can handle babili-standalone too. See https://github.com/babel/babel/blob/7.0/packages/babel-standalone/src/gulpTasks.js

_Sent from my Samsung SM-G950U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Daniel15** [comment]
We'll also need to copy across all the files from the current babili-standalone, such as the readme and its index.js file. You can find everything in the babel-standalone repo. Basically all we want to do is move the existing babili-standalone package across. Any refactoring can happen separately :) 

_Sent from my Samsung SM-G950U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by boopathi** [comment]
> If you like, I'll submit a PR to move across all the existing stuff since I'm familiar with how it's configured, and then we can iterate from there. :)

Sure. I just saw the discussion in babel too. I'll close this. Thanks.

**Comment by Daniel15** [comment]
Sorry for the thrash! We can come back to this later 😃 

You have some really good ideas here, like iterating over the `packages` directory to determine what to bundle (rather than hard-coding a list). This is a fantastic idea that we should do for babel-standalone too!

**Pull request closed without merging**
