### PR TITLE
Bugfix Regex's containing (\0)

### LINKED ISSUE #732: minify breaks jquery -> replaces \0 with NUL (Ascii)
Download jquery.min.js from https://code.jquery.com/jquery-3.2.1.min.js

Run Babel Minify on it.

Look at the result File and search for Ascii NUL -> you will find some

### PR DESCRIPTION
**Pull request by jogibear9988**
fixes #732

### CODE REVIEW

**Comment by jogibear9988** [comment]
Don't know why one test fails, I can't run them localy...

**Comment by jogibear9988** [comment]
@boopathi can you help me with the failing test?

**Comment by j-f1** [comment]
Have you considered instead optimizing the regex like it is done currently, then running `regexSource.replace(/\0/g, '\\0')`?

**Comment by j-f1** [comment]
Try running `yarn install --force`, then `yarn run fix` to fix the test failures.

**Comment by jogibear9988** [comment]
i‘ll try! thx!

**Comment by jogibear9988** [comment]
I thought about doing this, but I’ve not realy thought about what this module is doing, I only wanted to find what breaks.

**Comment by jogibear9988** [comment]
@j-f1 can you review?

**Comment by jogibear9988** [comment]
@boopathi failing tests now fixed, and unit test for functionality created!

**Pull request merged**
