### PR TITLE
optimize numeric literals properly [fixes #459]

### LINKED ISSUE #459: Number literal minification is suboptimal
Tested in the online repl:

Input:

```js
console.log(11000);
console.log(110000);
```

Expected output:

```js
console.log(11e3),console.log(11e4);
```

Actual output:

```js
console.log(11000),console.log(1.1e5);
```

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ combination of parseFloat and toExponential

### CODE REVIEW

**Comment by hzoo** [comment]
Hey @vigneshshanmugam! It looks like one or more of your builds have failed. I've copied the relevant info below to save you some time.

* [Node vnode - linux](https://travis-ci.org/babel/babili/jobs/209052487)

**Comment by vigneshshanmugam** [comment]
@hzoo Fixed it. Thanks :)

**Comment by vigneshshanmugam** [comment]
@boopathi There is a existing PR https://github.com/babel/babili/pull/349  which i just saw today, But it lacks some of the optimizations.. 

We should converge both and go with the one which will be better.

**Comment by hzoo** [comment]
Hey @vigneshshanmugam! It looks like one or more of your builds have failed. I've copied the relevant info below to save you some time.

* [Node vnode - linux](https://travis-ci.org/babel/babili/jobs/210344348)

**Comment by bardiharborow** [comment]
@vigneshshanmugam I've started updating my PR, and I'll work on merging the two.

**Comment by vigneshshanmugam** [comment]
Closing it in favour of #349

**Pull request closed without merging**
