### PR TITLE
Remove node 4. Add node 9

### PR DESCRIPTION
**Pull request by boopathi**
Ref: #766 - decision was made here.

Late to the game?

### CODE REVIEW

**Comment by azz** [comment]
Why is everyone dropping node 4 support so soon? I know LTS is ending next year,  but still seems early?

**Comment by boopathi** [comment]
@azz I'm not sure either.

**Comment by xtuc** [comment]
I was incredibly wrong, **Babel didn't dropped Node 4**.

> Node.js 0.10 and 0.12 has been dropped

**Comment by azz** [comment]
Babel dropped node v4 on the root package.json (i.e. just for development).

**Pull request merged**
